name: Reportar un error
description: Reportar un error de Alfa
body:
  - type: markdown
    attributes:
      value: |
        El soporte lo damos principalmente en el foro. Deberás seguir los mismos pasos del mismo para que atendamos tu reporte en GitHub.
        
        Si tienes algún problema con Alfa y deseas reportarlo, sigue esta guía para reportar correctamente un error y que el staff pueda ayudarte.
        
        ## Verifica
        Primero _**asegúrate de tener la última versión del addon**_. Si el problema es respecto a un canal o servidor en especifico, asegúrate de que puedes acceder a la pagina del canal y de que no sea un error de la pagina misma (ej. la página no abre o X sección cambió).
        
        Una vez te hayas asegurado de que el error del canal o servidor es exclusivo a Alfa, o bien el error es de algún componente interno de Alfa (autoplay, trakt, etc.), repórtalo siguiendo los pasos descritos a continuación.
  - type: checkboxes
    id: verified
    attributes:
      label: ¿Verificaste que el error es de Alfa?
      description: Verifica que el error solamente ocurre en Alfa y no en la web. Cuando el problema está en la web, no podemos hacer nada.
      options:
      - label: Verifiqué que el error solo es de Alfa
        required: true
  - type: markdown
    attributes:
      value: |
        ## Genera el reporte
        Cierra por completo Kodi (o lo que utilices), vuelve a abrirlo, espera un par de minutos, y ve al menú principal de Alfa.
        
        Si puedes entrar en Alfa y funciona mínimamente, selecciona la opción "Reportar un Fallo" y sigue los pasos descritos:
        1. Reproduce el problema​
        2. Vuelve al menú principal y vuelve a seleccionar "Reportar un Fallo"​
          1. Copia la dirección en la que se ha creado el informe​
          2. Reporta el problema en el foro como se describe en la siguiente sección, anexando la dirección de tu informe (la que se generó y copiaste en el paso anterior).​

        
        Si _**NO**_ puedes entrar en Alfa, lo mejor es que instales el add-on **Kodi Logfile Uploader** del repositorio de Kodi. Para ello sigue estos pasos:
        1. Desde el menú de **Add-ons**, selecciona **Instalar desde repositorio​**
        2. Selecciona el **Kodi Add-on repository​**
        3. Selecciona **Add-ons de programas​**
        4. Selecciona **Kodi Logfile Uploader** e instálalo​

        En Alfa:
        1. Activa **"Generar Log detallado"** desde el menú de Ajustes de Alfa. Esto es _**IMPRESCINDIBLE​**_
        2. **Reinicia Kodi**, espera un par de minutos, y **reproduce el problema** y vuelve al siguiente paso​
        3. Desde el menú Add-ons, Add-ons de programas, selecciona **Kodi Logfile Uploader​**
        4. Selecciona **Upload​**
        5. Copia el enlace que te muestra en pantalla, del estilo: _https://paste.kodi.tv/xyz​_
        6. **Reporta el problema** como se describe en la siguiente sección, **anexando la dirección de tu reporte** (la que se generó y copiaste en el paso anterior)​
        7. **Desactiva** _"Generar Log Detallado"_ en el menú de **Ajustes de Alfa​**
  - type: input
    id: log
    attributes:
      label: Enlace al reporte de error
      description: 'Ingresa el enlace al reporte de error generado con Alfa. Si por cualquier razón no puedes generar el enlace, escribe "No tengo enlace"'
      placeholder: https://logs.alfa-addon.com/ABCDEF123456
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Prepara el reporte
        Utilizar el buscador de GitHub para ver si ya existe alguna propuesta sobre tu problema en particular.
        - Si existiese, es ahí donde debes poner tu comentario lo mas detallado posible.
        - Si no existe ninguna propuesta relacionada con tu error, crea una nueva con los siguientes datos:
  - type: input
    id: os
    attributes:
      label: Sistema operativo
      description: Ingresa el sistema operativo en el que ejecutas Kodi y Alfa
      placeholder: Windows 10, Android TV 11, macOS 10.17, debian 12.1...
  - type: input
    id: alfa
    attributes:
      label: Versión de Alfa
      description: Esta siempre deberá ser la última. Considera esto un filtro para ver si tu error se debe a una versión desactualizada
      placeholder: 3.x.x
  - type: dropdown
    id: kodi
    attributes:
      label: Versión de Kodi
      description: Ingresa la versión de Kodi en la que te ocurre el error. Actualmente damos soporte a Kod 18, 19 y 20
      multiple: false
      options:
        - Kodi 18
        - Kodi 19
        - Kodi 20
        - Kodi 21
      default: 2
  - type: textarea
    id: description
    attributes:
      label: Descripción del problema
      description: Describe en qué consiste tu problema con Alfa
      placeholder: 
