# 2025 (C) Alfa Development Group
# Developed by SistemaRayoXP
name: Bump add-on version & release

on:
  workflow_dispatch:

permissions: write-all

env:
  GIT_USER_NAME: Alfa Development Group
  GIT_USER_EMAIL: 145614550+alfa-addon@users.noreply.github.com
  GITHUB_REPOSITORY: alfa-addon/addon
  ADDON: plugin.video.alfa

jobs:
  deploy:
    name: Deploy add-on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install environment tools
        working-directory: ${{ github.workspace }}
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet jq
          pip install -r requirements-ci.txt

      - name: Bump version and release on GitHub
        id: release
        working-directory: ${{ github.workspace }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(scripts/release.sh -qbcgv)
          ZIP_FILE=$(scripts/release.sh -qz)
          gh release create "Alfa-v$VERSION" "$ZIP_FILE"
          url=$(gh api repos/$GITHUB_REPOSITORY/releases/latest --jq '.assets[0].browser_download_url')
          echo "url=$url" >> $GITHUB_OUTPUT

      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ env.GITHUB_REPOSITORY }}
          event-type: update-repo
          client-payload: >-
            {
              "addon_id": "${{ env.ADDON }}",
              "url": "${{ steps.release.outputs.url }}"
            }
