# This is a basic workflow to help you get started with Actions
name: release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - devel
      # - /v\.\d+\.\d+\.\d+/
    paths:
        - '.github/workflows/*.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message == 'release' }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ADDON: 'plugin.video.alfa'

    steps:
      - name: Set-up Python version 
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Setting environment variables
        run: |
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          export ADDON='plugin.video.alfa'

      - name: Cloning repo
        run: git clone https://github.com/$GITHUB_REPOSITORY

      - name: Start deployment
        run: |
          echo "Changing to addon directory"
          cd addon
          echo "1: Download deployment script"
          wget https://raw.githubusercontent.com/alfa-addon/travis_scripts/master/deploy_addon.py
          echo "4: Create release"
          curl --request POST \
          --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          --header 'content-type: application/json' \
          --url https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
          --data '{
            "tag_name": "release-${{ github.run_id }}",
            "body": ""
            }' \
          --fail
